# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='дата и время')),
                ('name', models.CharField(blank=True, help_text='Нужно, чтобы быстро понимать, к чему относится дата', max_length=120, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'key dates',
                'verbose_name': 'key date',
            },
        ),
        migrations.CreateModel(
            name='KeyDateException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Новое время')),
                ('key_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='dates.KeyDate')),
                ('user', models.ForeignKey(help_text='Пользователь, для которого будет применено исключение', on_delete=django.db.models.deletion.CASCADE, related_name='key_date_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'key date exceptions',
                'verbose_name': 'key date exception',
            },
        ),
        migrations.AlterUniqueTogether(
            name='keydateexception',
            unique_together=set([('key_date', 'user')]),
        ),
    ]
